### ISSUE TITLE
url namepsace deliminators in prehash

### ISSUE THREAD

**Issue by Echsecutor** [RalphTro/epcis-event-hash-generator#18]
Namespace URLs should be surroundeed by "{" and "}" instead of postfixed by "#" to avoid confusion with "#" appearing in URLs.
@RalphTro  What do you think?

**Comment by RalphTro** [comment]
I like Mark's/your approach to work with sth. else than '#'. 
What is your reasoning to go for {} instead of what Mark suggested in his e-mail on this ("I'd suggest not using '#' but instead, either use an empty string or use a space character (space may not appear within a URI but is OK as a separator within data input to a hash function).")? 
Thanks in advance for sharing your thougts!

**Comment by Echsecutor** [comment]
I am not a fan of white space. Emptystring is fine for me. the "{" "}" is the canonical XML way to denote the namespace, hencewe follow an existing "standard". ;)

**Comment by RalphTro** [comment]
As you have more experience in that, I am agreeable with any appropriate way...so, please go ahead! ;-)

**Comment by Echsecutor** [comment]
@RalphTro this means that the example with the picture in the README needs to be changed. Sorry.
